### PR TITLE
modernize runit_service provider

### PR DESCRIPTION
**Pull request by someara**
Modernizing runit_service provider
 - Converting to LWRP DSL
 - Increading readability
 - Initial ChefSpec
 - Debian 7 now works
 - RHEL 7 support

Switching from Minitest to Serverspec
- Makes it easier to tell if resources update on 2nd and 3rd runs
- Integration tests not run in context of initial converge
- Utilize test-kitchen bussers

### CODE REVIEW

**Comment by jtimberman** [comment]
Awesome!

Let's get centos-7.0 and debian-7.8 into the default `.kitchen.yml`, as not everyone has DO :smile_cat:.

**Comment by jtimberman** [comment]
Also `ln -s Berksfile.disabled Berksfile` works a treat :cake:.

**Comment by someara** [comment]
added!

**Comment by luckymike** [comment]
@jtimberman getinsertpic.com

:+1:

**Comment by luckymike** [comment]
@someara could we get this as two PRs, the first to bring in the new tests, and the second with the LWRP changes? That would allow confirming that the old provider code works with the new tests, and then confirming that the new providers work with those tests (i.e. behavior is functionally intact). 

New tests and new providers at the same time is essentially a whole new cookbook, and we're limited by our ability to mentally parse the code and by manual smoke tests to ensure that new_thing == old_thing.

**Comment by someara** [comment]
#108 and #109

**Comment by cwjohnston** [comment]
Evaluating the split PRs took some time because not all tests in #108 pass. This is due to Gemfile changes that should be in #109, and needed ServerSpec changes that are present in #109.

That said, having the changes split out into logical chunks has helped me to digest these changes and I think I am comfortable merging this PR at once instead of piece meal.

Now that I've bumped development branch to 1.6.1 so that I can merge this PR, we've got a merge conflict.
@someara can you please rebase this on master to address the conflict?

**Comment by someara** [comment]
Your merge button is now green, sir.

**Comment by someara** [comment]
https://www.youtube.com/watch?v=KiQzUEc_FmI

**Pull request merged**
