### PR TITLE
Revert "Move log config file from log service dir into log dir"

### PR DESCRIPTION
**Pull request by slyness**
Reverts hw-cookbooks/runit#82

### CODE REVIEW

**Comment by slyness** [comment]
@mkropat This fails testing currently.  Let's take another pass at this.

```
      * Parent directory /var/log/plain-defaults does not exist.
      ================================================================================
      Error executing action `create` on resource 'template[/var/log/plain-defaults/config]'
      ================================================================================
```

```

           Chef::Exceptions::EnclosingDirectoryDoesNotExist
           ------------------------------------------------
           template[/var/log/plain-defaults/config] (dynamically defined) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory /var/log/plain-de
faults does not exist.
```

```
[2015-02-12T06:56:45+00:00] ERROR: runit_service[plain-defaults] (runit_test::service line 53) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: template[/var/log/plain-defaults/config] (dynamically defined) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory /var/log/plain-defaults does not exist.
```

**Comment by mkropat** [comment]
I'm having a heck of a time trying to get `bundle exec kitchen test` to run on my Linux Mint 17 box. It seems to be some conflict between the system vagrant and my rbenv instance of Ruby.

I'd love to see this through, but it might be a little while before I'll be in a place to do so.

**Comment by mkropat** [comment]
I took another crack at this today and I got test kitchen running on my Windows box.

But then I got stuck trying to make [a change to always create the log directory](https://github.com/mkropat/runit/commit/a22b7c45e644a50267e0bceaaa2708b119afcab9) (since the config file is always created there). The change causes the tests to fail with a weird error:

```
Failures:

  1) Chef::Provider::Service::Runit actions action_enable enables the service with memoized resource creation methods
     Failure/Error: provider.run_action(:enable)
     NameError:
       directory[/var/log/getty.service] (dynamically defined) had an error: NameError: uninitialized constant Chef::Pro
vider::File::Content
     # ./libraries/provider_runit_service.rb:124:in `configure_service'
     # ./libraries/provider_runit_service.rb:93:in `block in action_enable'
     # ./libraries/provider_runit_service.rb:92:in `action_enable'
     # ./test/spec/libraries/provider_runit_service_spec.rb:482:in `block (4 levels) in <top (required)>'

  2) Chef::Provider::Service::Runit actions action_enable new resource conditionals creates the env dir and config files
 if env is set
     Failure/Error: provider.run_action(:enable)
     NameError:
       directory[/var/log/getty.service] (dynamically defined) had an error: NameError: uninitialized constant Chef::Pro
vider::File::Content
     # ./libraries/provider_runit_service.rb:124:in `configure_service'
     # ./libraries/provider_runit_service.rb:93:in `block in action_enable'
     # ./libraries/provider_runit_service.rb:92:in `action_enable'
     # ./test/spec/libraries/provider_runit_service_spec.rb:661:in `block (5 levels) in <top (required)>'

  3) Chef::Provider::Service::Runit actions action_enable new resource conditionals creates the control dir and signal f
iles if control is set
     Failure/Error: provider.run_action(:enable)
     NameError:
       directory[/var/log/getty.service] (dynamically defined) had an error: NameError: uninitialized constant Chef::Pro
vider::File::Content
     # ./libraries/provider_runit_service.rb:124:in `configure_service'
     # ./libraries/provider_runit_service.rb:93:in `block in action_enable'
     # ./libraries/provider_runit_service.rb:92:in `action_enable'
     # ./test/spec/libraries/provider_runit_service_spec.rb:668:in `block (5 levels) in <top (required)>'
```

The stack trace gives me no clue as to why it's throwing that `NameError`.  So that's where I'm stuck, in case anyone's curious.

**Comment by cwjohnston** [comment]
This PR seems to be in an odd state following the merge of #107. Can you please retest the issue and adjust as needed?

**Comment by cwjohnston** [comment]
Closed by #135

**Pull request closed without merging**
