### PR TITLE
add a Berksfile

### PR DESCRIPTION
**Pull request by lamont-granquist**
has an integration group for testing with test-kitchen

### CODE REVIEW

**Comment by jtimberman** [comment]
:+1: - While I understand that HW uses librarian - hence this cookbook has a Cheffile -  ChefDK doesn't include librarian, and personally I'd rather avoid dealing with bundler just to run test kitchen for this cookbook.

**Comment by someara** [comment]
I shipped a Berksfile in #106. We should probably close this one to make merging easier

**Comment by webframp** [comment]
:thumbsup: good with me

Especially since #106 is a switch to serverspec and this one has minitest deps

**Comment by luckymike** [comment]
I'm :-1: on this at this time, I'll explain why:

test-kitchen currently looks for dep-solvers alphabetically. If both a Berksfile and Cheffile are present, it will look for Berks to be installed, and die-in-flames if it is not there, without ever hitting the Cheffile and checking for librarian. 

Adding a Berksfile will force everyone to have Berks installed. This would merely be annoying for non-Berks users, except Berks installation is handled with ChefDK, instead of bundler, meaning we need a global installation of duplicate tools.

**Comment by someara** [comment]
@fnichol is this still the case with the latest test-kitchen?

**Pull request closed without merging**
