### PR TITLE
Runit 1.5.20

### PR DESCRIPTION
**Pull request by slyness**

### CODE REVIEW

**Comment by slyness** [comment]
@jtimberman Since this will update the way runit is installed on RH and Centos systems to the new repository and rpm install should we release this as Minor version release?

**Comment by jtimberman** [comment]
Yeah I'd say 1.6 is apropos.

It should still be totally compatible with existing installations because all it will do is add the repository configuration - the rpm would already be installed and not affect the outcome of node convergence.

But before you merge this, I kind of want to get Fedora supported :cake:. I'm working on that for a personal project right now.

**Comment by jtimberman** [comment]
@imeyer is going to add fedora/21 to his packagecloud repo tomorrow so that runit packages will be available there. Then supporting fedora should be a simple matter of adding it to the conditionals where 'rhel' occurs.

**Comment by imeyer** [comment]
@slyness @jtimberman I added the Fedora 21 RPM a bit ago and tested on a Fedora 21 image. Spec was refactored to better support systemd-enabled systems so I'll get those changes in my runit-rpm repo for public consumption.

**Comment by jtimberman** [comment]
I have local changes I'm testing in the repo and I'll push a branch with them soon.

**Comment by jtimberman** [comment]
Commit c3d46bcf2c330e90aff8f1bb1e1701d57078cca8, PR #99.

**Comment by slyness** [comment]
Closing in favor of releasing 1.6.0 #101

**Pull request closed without merging**
