### PR TITLE
Remove support for EoL platforms and improve RHEL support

### PR DESCRIPTION
**Pull request by tas50**
This builds on #180 so ignore those commits.  This removes support for EoL platforms and includes yum-epel where necessary so add support for RHEL 5/6 without manually applying yum-epel.

### CODE REVIEW

**Comment by cwjohnston** [comment]
Please [see this comment](https://github.com/hw-cookbooks/runit/pull/180#issuecomment-194511926) re: Berksfile. Meant to post it in this issue :sweat:

**Comment by cwjohnston** [comment]
I'm moving this to 2.0.0 milestone. Even though these platforms that are no longer supported by the vendor, I believe this represents a breaking change.

**Comment by cwjohnston** [comment]
@tas50 most of this seems sound, but will you please consider reverting the renaming of Berksfile.disabled to Berksfile ? Also looks like we're missing emeril Rake tasks in your new Rakefile.

**Comment by tas50** [comment]
@cwjohnston Done. Let me know if you need anything else. I'm around to get some testing done before 2.0 ships too.

**Comment by cwjohnston** [comment]
Closing in favor of #194

**Pull request closed without merging**
