### PR TITLE
Allow runit services to set default state to 'down'

### LINKED ISSUE #104: Add ability to to flag a runit service as 'down' to prevent runsv from automatically starting it
Some services that can be managed by runit need to be able to be explicitly flagged as 'down' to prevent runsv from starting them automatically.  An example of this is runit managed ucarp VIPs. Please support adding `/etc/sv/<service>/down` files during service configuration.

### PR DESCRIPTION
**Pull request by boldfield**
Allow runsv managed process to set default state to down to prevent them
from being automatically started. Fixes #104

See: http://smarden.org/runit/runsv.8.html

### CODE REVIEW

**Comment by jtimberman** [comment]
How is this different than using the `:down` action?

**Comment by boldfield** [comment]
Using the down action actively brings the service down, where using a down file prevents runsv from automatically bringing the service up, say on reboot for instance.

**Comment by boldfield** [comment]
I was still on my commute when I added my previous comment, I'll add a little more color.

A specific example of where this is needed: we use ucarp to manage a set of VIPs using runit, which will issue an 'sv run' command on a given node when it is deemed that the node needs to take ownership of said set of VIPs.  In this setup we need to make sure that runsv _doen not_ automatically start the IP management processes on a system which was restarted, which would trigger an ARP broadcast and wreak havoc in our network....

**Comment by cwjohnston** [comment]
Hi Brian,

Looks like these changes pre-date recent refactoring around the `runit_service` provider. Can you please rebase your changes?

Thanks!

**Comment by boldfield** [comment]
Hi Cameron,

I've rebased the changes and updated the associated tests.

Thanks!

**Comment by boldfield** [comment]
There was some cruft from my rebase that wasn't apparent until I pushed.  That issue is now fixed.

**Comment by cwjohnston** [comment]
Sorry, I broke your rebase again by merging some other PRs. :sweat: 

I've merged this via cherry-pick in 8a5f16067291663af217a2a65fc712a93bf060c8. Thanks!

**Comment by boldfield** [comment]
Thanks!

**Pull request closed without merging**
