### PR TITLE
adding back in restart_on_update functionality

### PR DESCRIPTION
**Pull request by dcparker88**
regarding #145 this is an initial pass of adding back in that functionality. I tried to get it to work using `updated_by_last_action?` but was unable to get that working. If there's a better way to do this I am all for it.

### CODE REVIEW

**Comment by donaldguy** [comment]
+1

**Comment by dcparker88** [comment]
updated with some more changes I needed internally. I added in `action_enabled` before restarting to make sure the /etc/service directory exists before trying to restart

**Comment by manasg** [comment]
:+1:

**Comment by cwjohnston** [comment]
@dcparker88 can you please rebase this on current develop? Thanks!

**Comment by dcparker88** [comment]
rebased

**Comment by cwjohnston** [comment]
Resolves #145

**Comment by manasg** [comment]
Hi @cwjohnston 
When is this going out?

**Pull request closed without merging**
