### PR TITLE
Mark env files as sensitive

### PR DESCRIPTION
**Pull request by martinisoft**
This suppresses env file logging output in case of sensitive credentials making their way in to that directory. There is a fallback in case this is an older version of Chef that does not support sensitive as a common resource argument.

### CODE REVIEW

**Comment by cwjohnston** [comment]
Thanks for the PR @martinisoft. I tried to add the following test to validate this functionality, but it's not passing:

```ruby
it 'sets the sensitive attribute on the env file resource' do
  expect(chef_run).to create_file(::File.join(service_svdir, 'env', 'PATH')).with(
    :sensitive => true
   )
end
```

```
Failures:

  1) runit_service with environment attributes sets the sensitive attribute on the env file resource
     Failure/Error: expect(chef_run).to create_file(::File.join(service_svdir, 'env', 'PATH')).with(
       expected "file[/etc/sv/env-files/env/PATH]" to have parameters:

         sensitive true, was false
     # ./test/unit/runit_service/step_into_service_spec.rb:256:in `block (3 levels) in <top (required)>'
```
Also, I'm curious if there's a reason we're querying the instance methods on `Chef::Provider::ChefGem` rather than `Chef::Provider::File` ? FWIW I have tried the test both ways with no success.

Any thoughts about how to test for this?

**Comment by martinisoft** [comment]
@cwjohnston You're right and I've changed the class accordingly. A way you can test this by hand is to make a bundle with Chef 11.10 and run chef-shell with that code to see if it returns false then upgrade to 11.14 or newer and try again it should be true. The test should pass now with this change and if you'd like I can include it with my PR.

**Comment by cwjohnston** [comment]
Due to the particulars of our unit test specs, it is proving difficult to actually run the negative case test against Chef < 11.14, but the affirmative test against this latest commit looks good to me! :+1: 

@martinisoft, will you please add the affirmative unit test to this PR?

**Comment by martinisoft** [comment]
@cwjohnston I've added the test, but I am unable to run the specs locally. I keep seeing argument errors for the shared `chef_run` let so I don't know if this was a breaking change in ChefSpec that caused that.

**Comment by cwjohnston** [comment]
@martinisoft any connection to #185 ?

**Comment by martinisoft** [comment]
@cwjohnston That patch resolved my testing issue and I was able to correct my test to get it to pass. All ready for review and possible merge 👍

**Comment by cwjohnston** [comment]
Looks good to me! Thanks!

**Pull request merged**
